name: myBuild firmware

on:
  push:
    branches: ['**']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt update
          apt install make gcc sdcc xxd python-is-python3 libjson-c-dev -y
      - name: Check if machine.c can be compiled for all machines
        run: make machine_check
      - name: Make project
        run: make MACHINE="SWTGW218AS"
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v7
        with:
          name: SWTGW218AS
          path: output/
